In [83]:
import numpy as np

Question 2a

In [100]:
# Creates an array of random integers from 1 to 100 shaped 4x4
arr1 = np.array(np.ceil(np.random.random((4,4))*100), dtype='int')

# Creates an array of numbers from 1 to 16 shapes 4x4
arr2 = np.arange(1,17).reshape(4,4)

In [85]:
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)

2
16
(4, 4)


In [86]:
print(arr2.ndim)
print(arr2.size)
print(arr2.shape)

2
16
(4, 4)


Question 2b

In [87]:
np.dot(arr1, arr2)

array([[1003, 1130, 1257, 1384],
       [1065, 1254, 1443, 1632],
       [1836, 2056, 2276, 2496],
       [1439, 1626, 1813, 2000]])

In [88]:
result = np.log(np.dot(arr1, arr2))

In [89]:
np.save('cbento23_2b.npy', result)

In [90]:
print(np.mean(result))
print(np.std(result))

7.347031832990849
0.2645713784094067


Question 2c

In [91]:
result

array([[6.91075079, 7.02997291, 7.13648321, 7.23273314],
       [6.97073008, 7.13409372, 7.27447956, 7.39756154],
       [7.51534457, 7.62851763, 7.7301748 , 7.82244473],
       [7.27170371, 7.39387829, 7.50273821, 7.60090246]])

In [92]:
result[2][0]

7.515344571180436

In [93]:
newMatrix = result[0:2, 0:2]
newMatrix

array([[6.91075079, 7.02997291],
       [6.97073008, 7.13409372]])

In [94]:
np.mean(newMatrix[:, 1])

7.0820333164496265

Question 2d

In [95]:
result[result < np.mean(result)]

array([6.91075079, 7.02997291, 7.13648321, 7.23273314, 6.97073008,
       7.13409372, 7.27447956, 7.27170371])

Question 2e

In [96]:
horizontalArr = np.hstack((arr1, arr2))
horizontalArr.shape

(4, 8)

In [97]:
result

array([[6.91075079, 7.02997291, 7.13648321, 7.23273314],
       [6.97073008, 7.13409372, 7.27447956, 7.39756154],
       [7.51534457, 7.62851763, 7.7301748 , 7.82244473],
       [7.27170371, 7.39387829, 7.50273821, 7.60090246]])

In [98]:
# Splits the dot product array into two equal parts vertically.
[A, B] = np.vsplit(np.dot(arr1, arr2) ,2)
A

array([[1003, 1130, 1257, 1384],
       [1065, 1254, 1443, 1632]])

In [99]:
arr1

array([[10, 45, 42, 30],
       [80, 49, 10, 50],
       [33, 62, 33, 92],
       [67, 15, 17, 88]])