# Using Numpy

In [2]:
import numpy as np

# ndarray - N Dimensional Array <br>
Multidimensional homogenous array with predetermined size <br>
Data Type is specified by an object called 'dtype'

In [3]:
a = [[1,2,3,4], [2,3,4,5]]

### Creation of array using other datastructures

In [4]:
b = np.array(a, dtype='float')
b

array([[1., 2., 3., 4.],
       [2., 3., 4., 5.]])

In [5]:
type(b)

numpy.ndarray

In [6]:
b.dtype

dtype('float64')

In [7]:
b.shape

(2, 4)

In [8]:
b.ndim

2

In [9]:
b.size

8

### Intrinsic Creation of Array

In [10]:
a = np.zeros((3,3),dtype='int')
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [11]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# Gives elements starting at 0 and up to 10 (not including 10)
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Create an array with 'n' different parts.
c = np.linspace(2,10,4)
c

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])

In [14]:
#Reorganizing an array to a different structure
b = a.reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
# Create array with random numbers, defaults to numbers between 0 and 1.
r = np.random.random((3,3))
r

array([[0.52773831, 0.70414631, 0.43813799],
       [0.09307687, 0.80281688, 0.56191493],
       [0.79880312, 0.36310444, 0.13316561]])

In [16]:
np.array(np.ceil(r*100), dtype="int")

array([[53, 71, 44],
       [10, 81, 57],
       [80, 37, 14]])

### Array Operations
They are usually carried out element-wise

In [17]:
a * 4

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [18]:
a + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
b = np.random.random(10)

In [20]:
b

array([0.08023556, 0.65711383, 0.37038055, 0.80217099, 0.1106048 ,
       0.67540579, 0.14364116, 0.80468278, 0.82671549, 0.8151178 ])

In [21]:
a + b

array([0.08023556, 1.65711383, 2.37038055, 3.80217099, 4.1106048 ,
       5.67540579, 6.14364116, 7.80468278, 8.82671549, 9.8151178 ])

In [22]:
b * np.sin(a)

array([ 0.        ,  0.55294222,  0.33678608,  0.11320238, -0.08370599,
       -0.64766301, -0.04013557,  0.5286658 ,  0.81791779,  0.33592511])

In [23]:
b

array([0.08023556, 0.65711383, 0.37038055, 0.80217099, 0.1106048 ,
       0.67540579, 0.14364116, 0.80468278, 0.82671549, 0.8151178 ])

In [24]:
a += 1
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
b -= 1
b

array([-0.91976444, -0.34288617, -0.62961945, -0.19782901, -0.8893952 ,
       -0.32459421, -0.85635884, -0.19531722, -0.17328451, -0.1848822 ])

#### Matrix Product

In [26]:
b = a.reshape((2,5))

In [27]:
c = a.reshape((5,2))

In [28]:
np.dot(b,c)

array([[ 95, 110],
       [220, 260]])

#### Universal Function (ufunc)
A function operating on each 

In [29]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [30]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

#### Aggregate Function
Produce a single result after after performing operation on all elements in the array

In [31]:
a.sum()

55

In [32]:
a.max()

10

### Indexing, Slicing and Iteration

#### Indexing

In [33]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
a[4]

5

In [35]:
a[-7]

4

In [36]:
a[[1,6,9]]

array([ 2,  7, 10])

In [37]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [38]:
b[1,2]

8

#### Slicing

In [39]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
a[1:7:2]
#a[::2]

array([2, 4, 6])

In [41]:
b
#b[0:2,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [42]:
b[0:2,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
b[:,0:2]

array([[1, 2],
       [6, 7]])

In [44]:
b[1,2:6]

array([ 8,  9, 10])

#### Iterating an array

In [45]:
for i in a:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [46]:
for i in b:
    print(i)
#Here 'i' is a row

[1 2 3 4 5]
[ 6  7  8  9 10]


In [47]:
for i in b:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10


In [48]:
np.array(b.flat)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
# This does the same code as above, which is much faster than a nested for loop.
for i in b.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10


### Conditions and Boolean Arrays
A different way to select a subset of an array

In [50]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
a>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [52]:
# Gives an array of values that meet a > 5
a[a>5]

array([ 6,  7,  8,  9, 10])

### Shape Manipulation
Changing an array shape in place

In [53]:
a.shape = (2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [54]:
#turn it back into 1-D array
a=a.ravel()
a
#or
#a.shape = (10,)
#a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Array Manipulation
#### vstack() and hstack()

In [55]:
A = np.zeros((3,3))
A

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
B = np.ones((3,3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [57]:
# Vertically stacks matrices on top of each other.
np.vstack((A,B))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [58]:
# Horizontal Stack
np.hstack((A,B))

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [59]:
a = np.arange(0,8,5)
b = np.arange(2,10,5)
c = np.arange(4,12,5)
X = np.row_stack((a,b))
X

array([[0, 5],
       [2, 7]])

In [60]:
a

array([0, 5])

In [61]:
b

array([2, 7])

In [62]:
Y = np.column_stack((a,b))
Y

array([[0, 2],
       [5, 7]])

#### Splitting of arrays

In [63]:
X

array([[0, 5],
       [2, 7]])

In [64]:
# Split the array vertically (split the rows) into two equal parts
[B,C] = np.vsplit(X,2)
B
#C

array([[0, 5]])

In [65]:
# Split the array horizontally (split the columns into two equal parts)
[D,E] = np.hsplit(X,2)
D
#E

array([[0],
       [2]])

In [67]:
A = np.arange(20).reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [65]:

#more complicated way to split arrays: axis = 1 represents columns and axis = 0 represents rows.
np.split(A,[1,3,4],axis=1)

[array([[ 0],
        [ 5],
        [10],
        [15]]),
 array([[ 1,  2],
        [ 6,  7],
        [11, 12],
        [16, 17]]),
 array([[ 3],
        [ 8],
        [13],
        [18]]),
 array([[ 4],
        [ 9],
        [14],
        [19]])]

In [66]:
A = np.arange(20).reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#### Copies or Views of Objects
A view is a slice of the original array

In [67]:
a = np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [68]:
b = a
b

array([0, 2, 4, 6, 8])

In [69]:
a[1] = 0
a

array([0, 0, 4, 6, 8])

In [70]:
b

array([0, 0, 4, 6, 8])

In [ ]:
#An assignment merely does not create a new array
#A copy does that

In [71]:
a = np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [72]:
b = a.copy()
b

array([0, 2, 4, 6, 8])

In [73]:
a[4] = 0
a

array([0, 2, 4, 6, 0])

In [74]:
b

array([0, 2, 4, 6, 8])

#### Vectorization
Absence of explicit looping <br>
Make a code look more Mathematical <br>
Different from Functional Programming - <br>
Functional Programming facilitates parallel programming of functions <br>
Vectorization facilitates parallel programming of numerical operations on arrays 

In [75]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [76]:
b = np.arange(0,20,2).reshape(2,5)

In [77]:
b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [79]:
# Element-wise multiplication
a * b

array([[  0,   2,   8,  18,  32],
       [ 50,  72,  98, 128, 162]])

#### Broadcasting
carrying operations between arrays of incompatile shapes <br>

1) If the arrays do not have the same rank (number of dimensions), pad the smaller-dimensional array's shape with the ones on its left side.
2) Compare the sizes of corresponding dimensions.
    - If the sizes are equal, continue.
    - If one of the sizes is 1, stretch (or broadcast) that dimension to match the other.
    - If the sizes are different and neither is 1, raise a ValueError.


In [80]:
a = np.arange(6,9).reshape(3,1)

In [81]:
c = np.arange(0,3).reshape(1,3)
c

array([[0, 1, 2]])

In [82]:
a

array([[6],
       [7],
       [8]])

In [83]:
a+c

array([[ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10]])

#### Structured Arrays
Structures are user-defined datatypes.

In [84]:
structured = np.array([(1, "First", 0.5, 1+2j),(2, 'Second', 1.3, 2-2j),
(3, 'Third', 0.8, 1+3j)],dtype=('int,U10,float,complex'))

In [85]:
structured

array([(1, 'First', 0.5, 1.+2.j), (2, 'Second', 1.3, 2.-2.j),
       (3, 'Third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i8'), ('f1', '<U10'), ('f2', '<f8'), ('f3', '<c16')])

In [86]:
A = np.array(['apple','banana'],dtype=('str'))
A

array(['apple', 'banana'], dtype='<U6')

### Saving and loading files

In [87]:
np.save('array1.npy',A)

In [88]:
A1=np.load("array1.npy")
A1

array(['apple', 'banana'], dtype='<U6')